### ISSUE TITLE
Could minimap2 settings be recommended in documentation?

### ISSUE THREAD

**Issue by mpmargolis** [COMBINE-lab/oarfish#18]
Hi - thank you for producing such a great tool for long-read quantification! I browsed the minimap2 discussion/issues pages to see if anyone had a consensus on options for minimap2 when aligning to the transcriptome, but could not find much agreement (just a suggestion to use -ax map-ont for one user).

Could you share the minimap2 parameters you used when testing the functionality of Oarfish? For instance, NanoCount recommends `minimap2 -t 4 -ax map-ont -p 0 -N 10 transcriptome.fa.gz reads.fastq.gz` for direct-RNA with ONT.

What would you recommend for cDNA with PacBio? or ONT? Is it advisable to keep more secondary alignments (with -p 0 -N 10)?

Thank you!

**Comment by rob-p** [comment]
Hi @mpmargolis,

  Thanks for raising these questions.  Yes; we'll be happy to add `minimap2` recommendations to the documentation.

  My general recommendations would be as follows (but we'll give more context when we put it properly in the documentation).

-- for ONT data: `--eqx -N 100 -ax map-ont`
-- for PacBio data: `--eqx -N 100 -ax pacbio`

The `--eqx` isn't strictly necessary, but we may, in the future, start to make use of some information from the actual CIGAR strings themselves, and so it will be useful to have an encoding of matches vs. mismatches. Further, it may be reasonable to consider an even larger `-N` (the [TranSigner](https://www.biorxiv.org/content/10.1101/2024.04.13.589356v1.full) paper recommends `-N 181`).

The `-p` parameter is an interesting one, and we've not considered modifying the default there yet, but it may be worth exploration. If you've tried some different settings and noticed any differences, please do let us know.  The `-N` parameter will allow more secondary alignments, and I'd definitely recommend more than 10.  The thing is that alignment scores are used to downweight sub-optimal alignments fairly aggressively. So, while it's certainly worthwhile to report as many near-optimal alignments as may exist, it's not too important to retain alignments with highly sub-optimal alignment scores.

When running on directRNA ONT data, be sure to pass the `-d fw` flag to retain only forward strand alignments (this is the syntax used in the latest release v0.5 and forward).

--Rob

**Comment by rob-p** [comment]
We've added the above to the documentation now as well, so I'm closing this issue for now.
