### ISSUE TITLE
Where does the oarfish-installer.sh come from?

### ISSUE THREAD

**Issue by corneliusroemer** [COMBINE-lab/oarfish#22]
I was trying to see what the installer script is like before running it - but I couldn't find it in the repo. Where does it come from?

I'm talking about this script:

```
https://github.com/COMBINE-lab/oarfish/releases/download/v0.5.1/oarfish-installer.sh
```

**Comment by rob-p** [comment]
Hi @corneliusroemer,

  Thanks for the question!  This is generated by [`cargo-dist`](https://github.com/axodotdev/cargo-dist) which we use as part of our release management cycle.  It generates the pre-compiled binaries, as well as the installer script to download them for the appropriate architecture from the github releases page.

  You can find out all of the cargo-dist details in their GitHub repo. It's an (awesome) open-source tool that really helps make releasing rust projects easier.

Best,
Rob
