### ISSUE TITLE
Inferential replicates and .pq file creation

### ISSUE THREAD

**Issue by margaux-david** [COMBINE-lab/oarfish#34]
Hello !

I am new to these kind of analyses and have been running ``oarfish`` (v.0.6.2) with the following parameters/options: 
``--single-cell``, ``--alignments``, ``--model-coverage`` and ``--num-bootstraps``. I wanted to generate the .pq file for follow-up analyses, but it does not get generated. I tried setting ``--num-bootstraps`` to 30 and to 100, but no .pq file was created. I also tried with and without specifying ``--threads`` but still no luck...
Can you help me solve this issue? 

Thank you so much! 

Kind regards

**Comment by rob-p** [comment]
Hi @margaux-david,

  Thanks for raising this issue. Right now, inferential replicates are only output in bulk RNA seq quantification mode. While it would certainly be possible to provide this information in single cell, I'm not aware of any tool that can actually take advantage of this information (i.e. full inferential replicates for single-cell analysis). I'm curious what your target analysis and proposed pipeline are.

Best,
Rob

**Comment by margaux-david** [comment]
Hi 😊

Thank you for this quick reply. We wanted to use the oarfish output as input for EdgeR, using a ‘customized’ version of the catchSalmon function.
The data will be pseudobulked for some of the analyses, so running oarfish without the ‘—single-cell’ option may be an option in this case?

Kind regards,

Margaux
