### ISSUE TITLE
Feature request: read-level probabilities

### ISSUE THREAD

**Issue by andyjslee** [COMBINE-lab/oarfish#35]
Thank you for developing Oarfish! I think it would be helpful to add an option to output read-transcript probabilities for downstream analysis. Would it be possible to implement this in a future update? Thank you!

**Comment by rob-p** [comment]
Thanks @andyjslee. @zzare-umd & @NPSDC --- this should be pretty straightforward to implement, so lets try and get it implemented quickly. If one of you wants to take a stab, let me know. We can discuss exactly where the best place to put this would be.

**Comment by rob-p** [comment]
Hi @andyjslee, we have a draft implementation of this now. We'll do a little more testing and then ask you to test it out if you're willing (before we merge it back into main).

**Comment by andyjslee** [comment]
Hi @rob-p! Yes, I'd love to test it out! Thank you so much.

**Comment by rob-p** [comment]
This is not an option in v0.6.3, which was just released. Thanks for the idea @andyjslee and for testing it!
