### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by katsikora** [COMBINE-lab/oarfish#7]
Dear Developers,

I'm interested in trying out oarfish. I've tried installing it on our system via `curl --proto '=https' --tlsv1.2 -LsSf https://github.com/COMBINE-lab/oarfish/releases/download/v0.2.0/oarfish-installer.sh | sh`, but it errors out:
```
System glibc version (`2.17') is too old; using musl
ERROR: there isn't a package for x86_64-unknown-linux-musl-static
```
Our machines are running CentOS 7.

Would you be able to help me with this? 

Best wishes,

Katarzyna

**Comment by rob-p** [comment]
Hi @katsikora,

  It's also available via bioconda. Is that mechanism available in your usecase? The current linux binaries build on the most recent ubuntu, which may cause the glibc issue.

Best,
Rob

**Comment by katsikora** [comment]
Perfect, conda works for me. Thanks a bunch!

Yes, I'm aware of it and we're supposed to move to Rhel.

Best wishes,
Katarzyna
